apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-web
  template:
    metadata:
      labels:
        app: python-web
    spec:
      containers:
        - name: python-cont
          image: maieffat/jenkins  # Update with your image name
          ports:
            - containerPort: 5000  # Change to your app's port
