apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  ports:
    - port: 5000       # The port that the service will expose
      targetPort: 5000 # The port your application is running on in the container
      nodePort: 30000   # Optional: specify a specific NodePort or let Kubernetes assign one
  selector:
    app: python-web
